component: http
name: nextDemo
inputs:
  src:
    dist: ./
    hook: npm run build
    exclude:
      - .env
  faas:
    runtime: Nodejs16.13
    framework: nextjs
    name: ${name}
  apigw:
    protocols:
      - http
      - https
app: next
